spring:
  datasource:
    #    提交机器人测试，数据库
    url: "jdbc:mysql://localhost:3311/qrcodeLanding?characterEncoding=utf-8"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: "create-drop"
