version: '3.1'

services:

  qrcode_landing:
    image: mysql:5.7
    # image: mariadb:10.2
    hostname: mysql57
    ports:
      - "3311:3306"
    command: [ #使用 command 可以覆盖容器启动后默认执行的命令
      '--character-set-server=utf8mb4', #设置数据库表的数据集
      '--collation-server=utf8mb4_general_ci', #设置数据库表的数据集
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qrcodeLanding
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - net

  # eas_java:
  #   image: maven:3.6-openjdk-8
  #   image: maven:3.8.6-openjdk-8-slim

networks:
  net:
