server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://qrcodeLanding-db/qrcodeLanding?useUnicode=true&characterEncoding=utf-8"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      
app:
  systemUrl: "http://localhost:81/"
